Description: >
    Mrinmmoi Hossain
    VPC create yml file.

Resources:
    HelloVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: true
